/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    redirects: Redirect;
    'contact-submissions': ContactSubmission;
    clients: Client;
    deals: Deal;
    activities: Activity;
    'consultation-types': ConsultationType;
    'availability-rules': AvailabilityRule;
    'blackout-dates': BlackoutDate;
    consultations: Consultation;
    pages: Page;
    projects: Project;
    'case-studies': CaseStudy;
    services: Service;
    team: Team;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    clients: {
      submissions: 'contact-submissions';
      consultations: 'consultations';
      deals: 'deals';
      activities: 'activities';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'consultation-types': ConsultationTypesSelect<false> | ConsultationTypesSelect<true>;
    'availability-rules': AvailabilityRulesSelect<false> | AvailabilityRulesSelect<true>;
    'blackout-dates': BlackoutDatesSelect<false> | BlackoutDatesSelect<true>;
    consultations: ConsultationsSelect<false> | ConsultationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-styles': SiteStyle;
    'seo-defaults': SeoDefault;
    'capability-tiles': CapabilityTile;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-styles': SiteStylesSelect<false> | SiteStylesSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'capability-tiles': CapabilityTilesSelect<false> | CapabilityTilesSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'consultation-reminder': TaskConsultationReminder;
      'stale-lead-nudge': TaskStaleLeadNudge;
      'weekly-kpi-digest': TaskWeeklyKpiDigest;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Original static path (e.g. /images/...) this asset was imported from. Resolvers prefer it over the Blob CDN URL.
   */
  legacyUrl?: string | null;
  /**
   * Describe this media for accessibility and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage URL redirects. Hygiene utility available at /admin/redirect-hygiene.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  statusCode?: ('301' | '302') | null;
  isEnabled?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  eventType?: string | null;
  services?:
    | {
        service?: string | null;
        id?: string | null;
      }[]
    | null;
  eventDate?: string | null;
  location?: string | null;
  budget?: string | null;
  message: string;
  /**
   * Auto-linked client record.
   */
  client?: (number | null) | Client;
  /**
   * Deal created from this submission, if converted.
   */
  convertedToDeal?: (number | null) | Deal;
  status?: ('new' | 'contacted' | 'qualified' | 'converted' | 'archived') | null;
  source?: string | null;
  /**
   * Marketing attribution captured from the landing URL (first touch).
   */
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    gclid?: string | null;
  };
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Unified client/contact records. Auto-linked from contact submissions and consultation bookings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  source?: ('contact-form' | 'booking' | 'manual' | 'referral' | 'ads') | null;
  tags?: ('premium-production' | 'agency-partner' | 'rental' | 'repeat-client' | 'vip')[] | null;
  notes?: string | null;
  /**
   * First-touch attribution (e.g. google, newsletter, google-ads via gclid). Auto-set from intake UTM params.
   */
  acquisitionSource?: string | null;
  /**
   * First-touch UTM campaign. Auto-set from intake UTM params.
   */
  acquisitionCampaign?: string | null;
  /**
   * Auto-stamped by CRM activity (submissions, bookings, deals).
   */
  lastActivityAt?: string | null;
  /**
   * Contact form submissions linked to this client.
   */
  submissions?: {
    docs?: (number | ContactSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  consultations?: {
    docs?: (number | Consultation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  deals?: {
    docs?: (number | Deal)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  activities?: {
    docs?: (number | Activity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Booked consultations and discovery calls.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations".
 */
export interface Consultation {
  id: number;
  type: number | ConsultationType;
  startTime: string;
  endTime: string;
  timezone: string;
  clientName: string;
  clientEmail: string;
  clientCompany?: string | null;
  phone?: string | null;
  projectSummary?: string | null;
  status?: ('new' | 'confirmed' | 'cancelled' | 'completed') | null;
  source?: string | null;
  /**
   * Marketing attribution captured from the landing URL (first touch).
   */
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    gclid?: string | null;
  };
  /**
   * Auto-linked client record.
   */
  client?: (number | null) | Client;
  /**
   * Auto-set when the 24h reminder email is sent.
   */
  reminderSentAt?: string | null;
  /**
   * Auto-populated when synced to Google Calendar.
   */
  googleCalendarEventId?: string | null;
  /**
   * Auto-populated when a Google Meet conference is created.
   */
  googleMeetLink?: string | null;
  /**
   * Private admin notes.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Types of meetings prospects can book.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-types".
 */
export interface ConsultationType {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left blank.
   */
  slug: string;
  /**
   * Duration in minutes.
   */
  duration: number;
  description?: string | null;
  /**
   * Optional hex color (e.g. #FF5733) used in calendar views.
   */
  color?: string | null;
  isEnabled?: boolean | null;
  /**
   * Lower numbers appear first in booking type lists.
   */
  listOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Proposals and revenue pipeline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  client: number | Client;
  /**
   * Deal value in USD.
   */
  value?: number | null;
  stage: 'lead' | 'proposal-sent' | 'negotiating' | 'won' | 'lost';
  servicesInterested?: (number | Service)[] | null;
  eventDate?: string | null;
  expectedCloseDate?: string | null;
  lostReason?: string | null;
  proposalNotes?: string | null;
  /**
   * Auto-generated. Public proposal lives at /proposal/[token].
   */
  proposalToken?: string | null;
  /**
   * Content of the public proposal page. Moving the stage to "Proposal Sent" emails the client the link.
   */
  proposal?: {
    scopeItems?:
      | {
          title: string;
          description?: string | null;
          /**
           * USD.
           */
          price?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * e.g. "Design 2 weeks, fabrication 4 weeks, install 2 days."
     */
    timeline?: string | null;
    /**
     * Payment terms, deposit, cancellation, etc.
     */
    terms?: string | null;
    validUntil?: string | null;
  };
  /**
   * Auto-set when the proposal email goes out.
   */
  sentAt?: string | null;
  /**
   * Auto-set on the client's first view of the proposal page.
   */
  viewedAt?: string | null;
  /**
   * Set manually when the client accepts. Does not auto-close the deal.
   */
  acceptedAt?: string | null;
  /**
   * Auto-set when the deal is won or lost.
   */
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'review' | 'published') | null;
  isEnabled?: boolean | null;
  category?: string | null;
  /**
   * Page type determines the route template and tag associations.
   */
  pageType: 'service' | 'tech' | 'rental';
  /**
   * Technologies behind this capability — shown as chips on tech pages. Display-only, never used for matching.
   */
  tech?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first in listings.
   */
  listOrder?: number | null;
  /**
   * Optional hierarchy parent for grouped service navigation.
   */
  parent?: (number | null) | Service;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  capabilities?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Deprecated — use Content Blocks below.
   */
  body?:
    | {
        type: string;
        heading?: string | null;
        content?: string | null;
        items?:
          | {
              value?: string | null;
              question?: string | null;
              answer?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contentBlocks?:
    | (
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            heading?: string | null;
            media: number | Media;
            caption?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            heading?: string | null;
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            url: string;
            provider?: ('youtube' | 'vimeo' | 'instagram' | 'external') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            heading?: string | null;
            items: {
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            quote: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            label: string;
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              label: string;
              url: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBar';
          }
      )[]
    | null;
  relatedWork?:
    | {
        project?: (number | null) | Project;
        title?: string | null;
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  media?: {
    heroImage?: (number | null) | Media;
    heroImageLegacyUrl?: string | null;
    galleryImages?:
      | {
          media?: (number | null) | Media;
          legacyUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
    ogImageLegacyUrl?: string | null;
  };
  /**
   * Open published route for this service.
   */
  liveUrl?: string | null;
  /**
   * Open admin-session draft/private preview route for this service.
   */
  previewUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * Workflow state for editorial quality control.
   */
  status?: ('draft' | 'review' | 'published') | null;
  isEnabled?: boolean | null;
  /**
   * Lower numbers appear first in listings.
   */
  listOrder?: number | null;
  /**
   * Optional hierarchy parent for grouped project navigation.
   */
  parent?: (number | null) | Project;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    tags?:
      | {
          tag: string;
          id?: string | null;
        }[]
      | null;
  };
  metadata?: {
    client?: string | null;
    location?: string | null;
    locations?:
      | {
          location: string;
          id?: string | null;
        }[]
      | null;
    type?: string | null;
    partners?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    tech?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    techniques?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    materials?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    spec?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    software?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Services used on this project — drives service-page related work and the /work service tag cloud.
   */
  serviceTags?: (number | Service)[] | null;
  /**
   * Technologies used on this project — drives /tech pages. Display-only: never used for project↔project relatedness.
   */
  techTags?: (number | Service)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
    ogImageLegacyUrl?: string | null;
  };
  /**
   * Deprecated — use Content Blocks below.
   */
  body?:
    | {
        type: string;
        heading?: string | null;
        content?: string | null;
        items?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contentBlocks?:
    | (
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            heading?: string | null;
            media: number | Media;
            caption?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            heading?: string | null;
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            url: string;
            provider?: ('youtube' | 'vimeo' | 'instagram' | 'external') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            heading?: string | null;
            items: {
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            quote: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            label: string;
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              label: string;
              url: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBar';
          }
      )[]
    | null;
  images?:
    | {
        media?: (number | null) | Media;
        legacyUrl?: string | null;
        alt: string;
        filename?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        title: string;
        provider?: ('youtube' | 'instagram' | 'vimeo' | 'external') | null;
        url: string;
        embedUrl?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Open published route for this project.
   */
  liveUrl?: string | null;
  /**
   * Open admin-session draft/private preview route for this project.
   */
  previewUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Notes, tasks, and call/email log for clients and deals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  type: 'note' | 'call' | 'email' | 'meeting' | 'task';
  subject: string;
  body?: string | null;
  client?: (number | null) | Client;
  deal?: (number | null) | Deal;
  consultation?: (number | null) | Consultation;
  dueDate?: string | null;
  completed?: boolean | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recurring weekly windows when consultations can be booked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-rules".
 */
export interface AvailabilityRule {
  id: number;
  /**
   * E.g. "Weekday mornings" or "Portland hours".
   */
  label: string;
  dayOfWeek: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  startTime: string;
  endTime: string;
  /**
   * IANA timezone (e.g. America/Los_Angeles).
   */
  timezone: string;
  /**
   * Leave empty to allow all enabled consultation types.
   */
  consultationTypes?: (number | ConsultationType)[] | null;
  isEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Specific dates or times blocked off from booking.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blackout-dates".
 */
export interface BlackoutDate {
  id: number;
  /**
   * E.g. "Company holiday" or "Team offsite".
   */
  label: string;
  date: string;
  isAllDay?: boolean | null;
  /**
   * Required if not all day. HH:MM format.
   */
  startTime?: string | null;
  /**
   * Required if not all day. HH:MM format.
   */
  endTime?: string | null;
  reason?: string | null;
  isEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Editorial workflow state.
   */
  status?: ('draft' | 'review' | 'published') | null;
  isEnabled?: boolean | null;
  showInNav?: boolean | null;
  navLabel?: string | null;
  navOrder?: number | null;
  /**
   * Optional parent for hierarchy and breadcrumbs.
   */
  parent?: (number | null) | Page;
  /**
   * Optional content grouping for filtering in admin.
   */
  category?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  pagination?: {
    /**
     * Optional list page size for index pages.
     */
    pageSize?: number | null;
  };
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    subheadline?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
  };
  media?: {
    heroImage?: (number | null) | Media;
    heroImageLegacyUrl?: string | null;
    galleryImages?:
      | {
          media?: (number | null) | Media;
          legacyUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Contact page only.
   */
  address?: {
    company?: string | null;
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    country?: string | null;
    formatted?: string | null;
  };
  /**
   * Contact page only.
   */
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    phoneFormatted?: string | null;
  };
  /**
   * Contact page only.
   */
  social?: {
    youtube?: string | null;
    instagram?: string | null;
  };
  /**
   * Contact page only.
   */
  consultationForm?: {
    heading?: string | null;
    description?: string | null;
    submitLabel?: string | null;
    successMessage?: string | null;
    fields?:
      | {
          id: string;
          label: string;
          type?: ('text' | 'email' | 'select' | 'multiselect' | 'date' | 'textarea') | null;
          required?: boolean | null;
          placeholder?: string | null;
          options?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
        }[]
      | null;
  };
  /**
   * Contact page only.
   */
  emailSignup?: {
    heading?: string | null;
    description?: string | null;
    placeholder?: string | null;
    submitLabel?: string | null;
  };
  /**
   * Optional custom preview path. Defaults to slug route.
   */
  previewPath?: string | null;
  /**
   * Open published route for this page.
   */
  liveUrl?: string | null;
  /**
   * Open admin-session draft/private preview route for this page.
   */
  previewUrl?: string | null;
  blocks?:
    | (
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            heading?: string | null;
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            items: {
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  label: string;
                  icon?: string | null;
                  /**
                   * Tile image path (e.g. /images/capabilities/foo.jpg). Defaults to the curated tile for this label.
                   */
                  image?: string | null;
                  /**
                   * Tile link (e.g. /services/custom-fabrication). Defaults to the curated tile for this label.
                   */
                  link?: string | null;
                  textPosition?: ('center' | 'top' | 'bottom' | 'below' | 'hidden') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilitiesGrid';
          }
        | {
            heading?: string | null;
            columns?:
              | {
                  image?: string | null;
                  heading: string;
                  body: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'philosophy';
          }
        | {
            heading?: string | null;
            projects?: (number | Project)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredWork';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            label: string;
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            url: string;
            provider?: ('youtube' | 'vimeo' | 'instagram' | 'external') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              label: string;
              url: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBar';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'review' | 'published') | null;
  isEnabled?: boolean | null;
  /**
   * Lower numbers appear first in listings.
   */
  listOrder?: number | null;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    tags?:
      | {
          tag: string;
          id?: string | null;
        }[]
      | null;
  };
  metadata?: {
    client?: string | null;
    location?: string | null;
    type?: string | null;
    investmentRange?: string | null;
    partners?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
    ogImageLegacyUrl?: string | null;
  };
  body?:
    | {
        type: string;
        heading?: string | null;
        content?: string | null;
        items?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        media?: (number | null) | Media;
        legacyUrl?: string | null;
        alt: string;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        title: string;
        provider?: ('youtube' | 'instagram' | 'vimeo' | 'external') | null;
        url: string;
        embedUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Open published route for this case study.
   */
  liveUrl?: string | null;
  /**
   * Open admin-session draft/private preview route for this case study.
   */
  previewUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  slug: string;
  title: string;
  bio: string;
  status?: ('draft' | 'review' | 'published') | null;
  isEnabled?: boolean | null;
  order?: number | null;
  expertise?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  photo?: {
    media?: (number | null) | Media;
    legacyUrl?: string | null;
    alt?: string | null;
  };
  /**
   * Open published route for team page.
   */
  liveUrl?: string | null;
  /**
   * Open admin-session draft/private preview route for team page.
   */
  previewUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'consultation-reminder' | 'stale-lead-nudge' | 'weekly-kpi-digest';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'consultation-reminder' | 'stale-lead-nudge' | 'weekly-kpi-digest') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'consultation-types';
        value: number | ConsultationType;
      } | null)
    | ({
        relationTo: 'availability-rules';
        value: number | AvailabilityRule;
      } | null)
    | ({
        relationTo: 'blackout-dates';
        value: number | BlackoutDate;
      } | null)
    | ({
        relationTo: 'consultations';
        value: number | Consultation;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  legacyUrl?: T;
  alt?: T;
  caption?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  isEnabled?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  eventType?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  eventDate?: T;
  location?: T;
  budget?: T;
  message?: T;
  client?: T;
  convertedToDeal?: T;
  status?: T;
  source?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        gclid?: T;
      };
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  source?: T;
  tags?: T;
  notes?: T;
  acquisitionSource?: T;
  acquisitionCampaign?: T;
  lastActivityAt?: T;
  submissions?: T;
  consultations?: T;
  deals?: T;
  activities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  value?: T;
  stage?: T;
  servicesInterested?: T;
  eventDate?: T;
  expectedCloseDate?: T;
  lostReason?: T;
  proposalNotes?: T;
  proposalToken?: T;
  proposal?:
    | T
    | {
        scopeItems?:
          | T
          | {
              title?: T;
              description?: T;
              price?: T;
              id?: T;
            };
        timeline?: T;
        terms?: T;
        validUntil?: T;
      };
  sentAt?: T;
  viewedAt?: T;
  acceptedAt?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  type?: T;
  subject?: T;
  body?: T;
  client?: T;
  deal?: T;
  consultation?: T;
  dueDate?: T;
  completed?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-types_select".
 */
export interface ConsultationTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  duration?: T;
  description?: T;
  color?: T;
  isEnabled?: T;
  listOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-rules_select".
 */
export interface AvailabilityRulesSelect<T extends boolean = true> {
  label?: T;
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  timezone?: T;
  consultationTypes?: T;
  isEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blackout-dates_select".
 */
export interface BlackoutDatesSelect<T extends boolean = true> {
  label?: T;
  date?: T;
  isAllDay?: T;
  startTime?: T;
  endTime?: T;
  reason?: T;
  isEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations_select".
 */
export interface ConsultationsSelect<T extends boolean = true> {
  type?: T;
  startTime?: T;
  endTime?: T;
  timezone?: T;
  clientName?: T;
  clientEmail?: T;
  clientCompany?: T;
  phone?: T;
  projectSummary?: T;
  status?: T;
  source?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        gclid?: T;
      };
  client?: T;
  reminderSentAt?: T;
  googleCalendarEventId?: T;
  googleMeetLink?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  isEnabled?: T;
  showInNav?: T;
  navLabel?: T;
  navOrder?: T;
  parent?: T;
  category?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  pagination?:
    | T
    | {
        pageSize?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
        ogImage?: T;
      };
  media?:
    | T
    | {
        heroImage?: T;
        heroImageLegacyUrl?: T;
        galleryImages?:
          | T
          | {
              media?: T;
              legacyUrl?: T;
              id?: T;
            };
      };
  address?:
    | T
    | {
        company?: T;
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
        formatted?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        phoneFormatted?: T;
      };
  social?:
    | T
    | {
        youtube?: T;
        instagram?: T;
      };
  consultationForm?:
    | T
    | {
        heading?: T;
        description?: T;
        submitLabel?: T;
        successMessage?: T;
        fields?:
          | T
          | {
              id?: T;
              label?: T;
              type?: T;
              required?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
      };
  emailSignup?:
    | T
    | {
        heading?: T;
        description?: T;
        placeholder?: T;
        submitLabel?: T;
      };
  previewPath?: T;
  liveUrl?: T;
  previewUrl?: T;
  blocks?:
    | T
    | {
        intro?:
          | T
          | {
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilitiesGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    image?: T;
                    link?: T;
                    textPosition?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        philosophy?:
          | T
          | {
              heading?: T;
              columns?:
                | T
                | {
                    image?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuredWork?:
          | T
          | {
              heading?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              heading?: T;
              url?: T;
              provider?: T;
              id?: T;
              blockName?: T;
            };
        ctaBar?:
          | T
          | {
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  isEnabled?: T;
  listOrder?: T;
  parent?: T;
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
      };
  metadata?:
    | T
    | {
        client?: T;
        location?: T;
        locations?:
          | T
          | {
              location?: T;
              id?: T;
            };
        type?: T;
        partners?:
          | T
          | {
              name?: T;
              id?: T;
            };
        tech?:
          | T
          | {
              value?: T;
              id?: T;
            };
        techniques?:
          | T
          | {
              value?: T;
              id?: T;
            };
        materials?:
          | T
          | {
              value?: T;
              id?: T;
            };
        spec?:
          | T
          | {
              value?: T;
              id?: T;
            };
        software?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  serviceTags?: T;
  techTags?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
        ogImage?: T;
        ogImageLegacyUrl?: T;
      };
  body?:
    | T
    | {
        type?: T;
        heading?: T;
        content?: T;
        items?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  contentBlocks?:
    | T
    | {
        text?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              heading?: T;
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              heading?: T;
              url?: T;
              provider?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        ctaBar?:
          | T
          | {
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  images?:
    | T
    | {
        media?: T;
        legacyUrl?: T;
        alt?: T;
        filename?: T;
        note?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        title?: T;
        provider?: T;
        url?: T;
        embedUrl?: T;
        note?: T;
        id?: T;
      };
  liveUrl?: T;
  previewUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  isEnabled?: T;
  listOrder?: T;
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
      };
  metadata?:
    | T
    | {
        client?: T;
        location?: T;
        type?: T;
        investmentRange?: T;
        partners?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
        ogImage?: T;
        ogImageLegacyUrl?: T;
      };
  body?:
    | T
    | {
        type?: T;
        heading?: T;
        content?: T;
        items?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  images?:
    | T
    | {
        media?: T;
        legacyUrl?: T;
        alt?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        title?: T;
        provider?: T;
        url?: T;
        embedUrl?: T;
        id?: T;
      };
  liveUrl?: T;
  previewUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  isEnabled?: T;
  category?: T;
  pageType?: T;
  tech?:
    | T
    | {
        value?: T;
        id?: T;
      };
  listOrder?: T;
  parent?: T;
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  capabilities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  body?:
    | T
    | {
        type?: T;
        heading?: T;
        content?: T;
        items?:
          | T
          | {
              value?: T;
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  contentBlocks?:
    | T
    | {
        text?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              heading?: T;
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              heading?: T;
              url?: T;
              provider?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        ctaBar?:
          | T
          | {
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  relatedWork?:
    | T
    | {
        project?: T;
        title?: T;
        slug?: T;
        id?: T;
      };
  media?:
    | T
    | {
        heroImage?: T;
        heroImageLegacyUrl?: T;
        galleryImages?:
          | T
          | {
              media?: T;
              legacyUrl?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
        ogImage?: T;
        ogImageLegacyUrl?: T;
      };
  liveUrl?: T;
  previewUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  bio?: T;
  status?: T;
  isEnabled?: T;
  order?: T;
  expertise?:
    | T
    | {
        value?: T;
        id?: T;
      };
  photo?:
    | T
    | {
        media?: T;
        legacyUrl?: T;
        alt?: T;
      };
  liveUrl?: T;
  previewUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Primary site navigation links shown in header/footer. Keep paths internal (start with /).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        enabled?: boolean | null;
        label: string;
        /**
         * Internal route path. Example: /work or /services/led-video-wall-rentals
         */
        path: string;
        /**
         * Lower numbers appear first.
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand-level visual settings used by frontend rendering.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-styles".
 */
export interface SiteStyle {
  id: number;
  /**
   * Hex color only.
   */
  brandPrimary?: string | null;
  /**
   * Hex color only.
   */
  brandSecondary?: string | null;
  /**
   * Hex color only.
   */
  backgroundColor?: string | null;
  fontFamilyHeading?: string | null;
  fontFamilyBody?: string | null;
  /**
   * Controls default button corner style.
   */
  buttonStyle?: ('sharp' | 'rounded') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Fallback SEO settings used when page-level values are missing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  siteName?: string | null;
  defaultTitle?: string | null;
  /**
   * Use %s placeholder for the page title.
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  /**
   * Default social image when a page has no custom OG image.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * If enabled, new pages default to noindex unless overridden.
   */
  noindexByDefault?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The image tile grid on the Services page ("Our Services"). Editable inline on /services in edit mode.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capability-tiles".
 */
export interface CapabilityTile {
  id: number;
  items?:
    | {
        label: string;
        /**
         * Tile image path (e.g. /images/capabilities/foo.jpg).
         */
        image?: string | null;
        /**
         * Tile link (e.g. /services/custom-fabrication).
         */
        link?: string | null;
        textPosition?: ('center' | 'top' | 'bottom' | 'below' | 'hidden') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        enabled?: T;
        label?: T;
        path?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-styles_select".
 */
export interface SiteStylesSelect<T extends boolean = true> {
  brandPrimary?: T;
  brandSecondary?: T;
  backgroundColor?: T;
  fontFamilyHeading?: T;
  fontFamilyBody?: T;
  buttonStyle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteName?: T;
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  noindexByDefault?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capability-tiles_select".
 */
export interface CapabilityTilesSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        image?: T;
        link?: T;
        textPosition?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskConsultation-reminder".
 */
export interface TaskConsultationReminder {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskStale-lead-nudge".
 */
export interface TaskStaleLeadNudge {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskWeekly-kpi-digest".
 */
export interface TaskWeeklyKpiDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}